Tercera_pre_entrega_Rojas_Torrilla/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('inicio/', include('inicio.urls')),
    path('admin/', admin.site.urls),
]

inicio/urls.py
from django.urls import path
from inicio import views

app_name = 'inicio'

urlpatterns = [
    path('', views.mi_vista, name='inicio'),
    path('crear-remera/', views.crear_remera, name='crear_remera'),
    path('remeras/', views.lista_remeras, name='listar_remeras'),
]

inicio/models.py
from django.db import models

# Create your models here.

class Remera(models.Model):
    modelo = models.CharField(max_length=20)
    talle = models.CharField(max_length=5)
    disenio = models.CharField(max_length=20)
    origen = models.CharField(max_length=20)
    
    def __str__(self):
        return f'El modelo es "{self.modelo}" con diseño de "{self.disenio}", talle: "{self.talle}". Origen: "{self.origen}".'
    
# class Remera(models.Model):
#     modelo = models.CharField(max_length=20)
#     talle = models.CharField(max_length=5)
#     diseño = models.CharField(max_length=20)
#     origen = models.CharField(max_length=20)

#     def __str__(self):
#         table = "| {:<10} | {:<5} | {:<20} | {:<20} |\n".format("Modelo", "Talle", "Diseño", "Origen")
#         table += "| {:<10} | {:<5} | {:<20} | {:<20} |\n".format("-"*10, "-"*5, "-"*20, "-"*20)
#         table += "| {:<10} | {:<5} | {:<20} | {:<20} |\n".format(self.modelo, self.talle, self.diseño, self.origen)
#         table += "\n"
#         return table
#hice esta clase, pero no se veía correctamente en el admin. Supongo que es una limitacion de la visualizacion.

inicio/forms.py
from django import forms

#form para remera, utilizo un placeholder
class CreacionRemeraFormulario(forms.Form):
    modelo = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'placeholder': 'Manga Corta, Manga Larga'}))
    talle = forms.CharField(max_length=5, widget=forms.TextInput(attrs={'placeholder': 's, m, l, xl, xxl'}))
    disenio = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'placeholder': 'One Piece, Pokemon, etc'}))
    origen = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'placeholder': 'China, Japon, etc'}))

#form para realizar busqueda del objeto remera, utilizando el diseño
class BuscarRemera(forms.Form):
    # permite que el campo este vacío
    disenio = forms.CharField(max_length=20, required=False)

inicio/views.py
from django.shortcuts import render, redirect
from inicio.models import Remera
from inicio.forms import CreacionRemeraFormulario, BuscarRemera

#vista de inicio
def mi_vista(request):
    return render(request, 'index.html')

#vista para crear el objeto remera mediante uso de formularoi
def crear_remera(request):
    if request.method == "POST":
        formulario = CreacionRemeraFormulario(request.POST)
        
        #utilizo las validaciones de Django
        if formulario.is_valid():
            datos_correctos= formulario.cleaned_data
            
            remera = Remera(modelo=datos_correctos['modelo'], talle=datos_correctos['talle'], disenio=datos_correctos['disenio'], origen=datos_correctos['origen'])
            remera.save()
            
            return redirect(r'inicio:listar_remeras')
    
    formulario = CreacionRemeraFormulario()
    return render(request, r'crear_remera.html', {'formulario': formulario})

#vista del listado de remeras creadas
def lista_remeras(request):
    nombre_a_buscar = request.GET.get('disenio', None)
    
    if nombre_a_buscar:
        remeras = Remera.objects.filter(disenio__icontains=nombre_a_buscar)
    else:
        remeras = Remera.objects.all()
    formulario_busqueda = BuscarRemera()
    return render(request, r'lista_remeras.html', {'remeras': remeras,'formulario': formulario_busqueda})

inicio/templates/crear_remera.html
{% extends 'base.html' %}

{% block title_head %}
<title>Crear Remera</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Ingrese los datos para crear el objeto Remera</h1>
{% endblock h1_header %}

{% block p_header %}
<form action={% url 'inicio:crear_remera' %} method="POST">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Crear</button>
</form>
{% endblock p_header %}

inicio/templates/index.html
{% extends 'base.html' %}

{% block title_head %}
<title>Inicio</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Bienvenidos a mi pagina principal</h1>
{% endblock h1_header %}

{% block p_header %}
<p class="lead text-secondary">Desarrollada por Lautaro Rojas Torrilla en Django</p>
{% endblock p_header %}

inicio/templates/lista_remeras.html
{% extends 'base.html' %}

{% block title_head %}
<title>Remeras</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Listado de Remeras</h1>
{% endblock h1_header %}

{% block p_header %}
<p>
    <form action={% url 'inicio:listar_remeras' %} method="get">
        {{formulario}}
        <button>Buscar</button>
    </form>
</p>
{% if remeras %}
    {% for remera in remeras %}
    <li>
        Diseño: {{remera.disenio}} - Modelo: {{remera.modelo}} - Talle: {{remera.talle}} - Origen: {{remera.origen}}
    </li>
    {% endfor %}
{% else %}
    <h2>No hay datos ingresados.</h2>
{% endif %}
{% endblock p_header %}

templates/base.html
<!doctype html>
{% load static %}
<html class="h-100" lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
  <meta name="description" content="A well made and handcrafted Bootstrap 5 template">
  <link rel="apple-touch-icon" sizes="180x180" href={% static 'inicio/img/apple-touch-icon.png' %}>
  <link rel="icon" type="image/png" sizes="32x32" href={% static 'inicio/img/favicon-32x32.png' %}>
  <link rel="icon" type="image/png" sizes="16x16" href={% static 'inicio/img/favicon-16x16.png' %}>
  <link rel="icon" type="image/png" sizes="96x96" href={% static 'inicio/img/favicon.png' %}>
  <meta name="author" content="Holger Koenemann">
  <meta name="generator" content="Eleventy v2.0.0">
  <meta name="HandheldFriendly" content="true">
  {% block title_head %}
  <title>Template Base</title>
  {% endblock title_head %}
  <link rel="stylesheet" href={% static 'inicio/css/theme.min.css' %}>

  <style>
    /* inter-300 - latin */
    @font-face {
      font-family: 'Inter';
      font-style: normal;
      font-weight: 300;
      font-display: swap;
      src: local(''),
        url({% static 'inicio/fonts/inter-v12-latin-300.woff2' %}) format('woff2'),
        /* Chrome 26+, Opera 23+, Firefox 39+ */
        url({% static 'inicio/fonts/inter-v12-latin-300.woff' %}) format('woff');
      /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }

    /* inter-400 - latin */
    @font-face {
      font-family: 'Inter';
      font-style: normal;
      font-weight: 400;
      font-display: swap;
      src: local(''),
        url({% static 'inicio/fonts/inter-v12-latin-regular.woff2' %}) format('woff2'),
        /* Chrome 26+, Opera 23+, Firefox 39+ */
        url({% static 'inicio/fonts/inter-v12-latin-regular.woff' %}) format('woff');
      /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }

    @font-face {
      font-family: 'Inter';
      font-style: normal;
      font-weight: 500;
      font-display: swap;
      src: local(''),
        url({% static 'inicio/fonts/inter-v12-latin-500.woff2' %}) format('woff2'),
        /* Chrome 26+, Opera 23+, Firefox 39+ */
        url({% static 'inicio/fonts/inter-v12-latin-500.woff' %}) format('woff');
      /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }

    @font-face {
      font-family: 'Inter';
      font-style: normal;
      font-weight: 700;
      font-display: swap;
      src: local(''),
        url({% static 'inicio/fonts/inter-v12-latin-700.woff2' %}) format('woff2'),
        /* Chrome 26+, Opera 23+, Firefox 39+ */
        url({% static 'inicio/fonts/inter-v12-latin-700.woff' %}) format('woff');
      /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }
  </style>
</head>

<body class="bg-black text-white mt-0" data-bs-spy="scroll" data-bs-target="#navScroll">

  <nav id="navScroll" class="navbar navbar-dark bg-black fixed-top px-vw-5" tabindex="0">
    <div class="container">
      <a class="navbar-brand pe-md-4 fs-4 col-12 col-md-auto text-center" href={% static 'index.html' %}>
        <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-stack"
          viewBox="0 0 16 16">
          <path
            d="m14.12 10.163 1.715.858c.22.11.22.424 0 .534L8.267 15.34a.598.598 0 0 1-.534 0L.165 11.555a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.66zM7.733.063a.598.598 0 0 1 .534 0l7.568 3.784a.3.3 0 0 1 0 .535L8.267 8.165a.598.598 0 0 1-.534 0L.165 4.382a.299.299 0 0 1 0-.535L7.733.063z" />
          <path
            d="m14.12 6.576 1.715.858c.22.11.22.424 0 .534l-7.568 3.784a.598.598 0 0 1-.534 0L.165 7.968a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.659z" />
        </svg>
        <span class="ms-md-1 mt-1 fw-bolder me-md-5">3ra PRE ENTREGA</span>
      </a>
      <ul class="navbar-nav justify-content-end mb-2 mb-lg-0 list-group list-group-horizontal">
        <li class="nav-item">
          <a class="nav-link fs-5" href={% url 'inicio:inicio' %} aria-label="Homepage">
            Inicio
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link fs-5" href={% url 'inicio:crear_remera' %} aria-label="A sample content page">
            Crear Remera
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link fs-5" href={% url 'inicio:listar_remeras' %} aria-label="A system message page">
            Remeras
          </a>
        </li>
      </ul>
    </div>
  </nav>

  {% block main_block %}
  <main>
    <div class="w-100 overflow-hidden position-relative bg-black text-white" data-aos="fade">
      <div class="position-absolute w-100 h-100 bg-black opacity-75 top-0 start-0"></div>
      <div class="container py-vh-4 position-relative mt-5 px-vw-5 text-center">
        <div class="row d-flex align-items-center justify-content-center py-vh-5">
          <div class="col-12 col-xl-10">
            {% block h1_header %}
            <h1 class="display-huge mt-3 mb-3 lh-1">Este es el h1 base!</h1>
            {% endblock h1_header %}
          </div>
          <div class="col-12 col-xl-8">
            {% block p_header %}
            <p class="lead text-secondary">Parrafo Base</p>
            {% endblock p_header %}
          </div>
        </div>
      </div>
    </div>
  </main>
  {% endblock main_block %}

  <footer class="bg-black border-top border-dark">
    <div class="container py-vh-4 text-secondary fw-lighter">
      <div class="row">
        <div class="col-12 col-lg-5 py-4 text-center text-lg-start">
          <a class="navbar-brand pe-md-4 fs-4 col-12 col-md-auto text-center" href="https://github.com/LautaroRojasTorrilla">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-stack"
              viewBox="0 0 16 16">
              <path
                d="m14.12 10.163 1.715.858c.22.11.22.424 0 .534L8.267 15.34a.598.598 0 0 1-.534 0L.165 11.555a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.66zM7.733.063a.598.598 0 0 1 .534 0l7.568 3.784a.3.3 0 0 1 0 .535L8.267 8.165a.598.598 0 0 1-.534 0L.165 4.382a.299.299 0 0 1 0-.535L7.733.063z" />
              <path
                d="m14.12 6.576 1.715.858c.22.11.22.424 0 .534l-7.568 3.784a.598.598 0 0 1-.534 0L.165 7.968a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.659z" />
            </svg>
            <span class="ms-md-1 mt-1 fw-bolder me-md-5">Rojas Torrilla</span>
          </a>
        </div>
      </div>
    </div>
  </footer>








  <script src={% static 'inicio/js/bootstrap.bundle.min.js' %}></script>
  <script src={% static 'inicio/js/aos.js' %}></script>
  <script>
    AOS.init({
      duration: 800, // values from 0 to 3000, with step 50ms
    });
  </script>
  <script>
    let scrollpos = window.scrollY;
    const header = document.querySelector(".navbar");
    const header_height = header.offsetHeight;

    const add_class_on_scroll = () => header.classList.add("scrolled", "shadow-sm");
    const remove_class_on_scroll = () => header.classList.remove("scrolled", "shadow-sm");

    window.addEventListener('scroll', function () {
      scrollpos = window.scrollY;

      if (scrollpos >= header_height) { add_class_on_scroll(); }
      else { remove_class_on_scroll(); }

      console.log(scrollpos);
    })
  </script>

</body>

</html>